### ISSUE TITLE
resizable

### ISSUE THREAD

**Issue by ricoderks** [rstudio/gridlayout#15]
Hi,

I just discovered this package after a tip! Looks awesome! I was wondering if you also have any plans of making the panels resizable. I mean like the panels in Rstudio. If you have 2x2 grid and if you e.g. resize vertically one side gets smaller and the otherside automatically becomes bigger.

Cheers, Rico

**Comment by nstrayer** [comment]
This is an interesting idea. We do have that exact feature in the shinyuieditor for setting the sizes of the panels. Wouldn't be too hard to implement it into gridlayout. It would require adding an addition bit of javascript that runs but it's not too much. 

I'm going to leave this open and circle back to it next time I have free time for to work on it because I think it's a good idea!

**Comment by nstrayer** [comment]
Does the new `full_screen` option in the `grid_card` (and accordingly `bslib::card()`) solve this usecase? It's not precise in it's expansion but does allow you to zoom into a part of the app.

**Comment by nstrayer** [comment]
Awesome! Thanks. I'll close this now but feel free to reopen if you feel necessary!
