### ISSUE TITLE
Changing `grid_card` collapsible behaviour

### ISSUE THREAD

**Issue by MikeJohnPage** [rstudio/gridlayout#18]
When a `grid_card()` is made collapsible, I think the default behaviour doesn't match what one may expect. Specifically, I would expect the card to act like a standard accordion (e.g., like the [Bootstrap v5.0 accordion](https://getbootstrap.com/docs/5.0/components/accordion/)) in that:

- The card/accordion is collapsed by default if `collapsible = true` (i.e.,  it can be expanded only if a user wants to discover more information)
- Any part of the the title of the card can be clicked to expand/collapse the card, not just the small arrow symbol as is currently implemented

I just wanted to pass on the feedback in case useful, as personally I would benefit from the default behaviour changing. Thanks!

**Comment by MikeJohnPage** [comment]
Concerning making a `grid_card` collapsed by default (if `collapsible = TRUE`), I found a temporary work around, which is to append the word "collapsed" to the class of the card to trigger the collapisble behaviour like so:

```r
grid_card() |>
  tagAppendAttributes(class = "collapsed")
```

Is there a less hacky way to do this? It appears that [this](https://github.com/rstudio/gridlayout/blob/main/R/grid_card.R#L62) is the code controlling the addition/removal of the word "collapsed" to the class, but I can't see a way to alter the default behaviour?

**Comment by MikeJohnPage** [comment]
Likewise, to make any part of the title card expandable/collapsible upon clicking, I found another temporary workaround which is to wrap the card title in a modified version of the span used in [`R/grid_card.R`](https://github.com/rstudio/gridlayout/blob/main/R/grid_card.R#L54):

```r
grid_card(
  title = shiny::span(
    "onclick" = '
    var card = this.parentElement.parentElement;
    var card_classes = card.classList;
    if (card_classes.contains("collapsed")) {
      card_classes.remove("collapsed");
    } else {
      card_classes.add("collapsed");
    }
    window.dispatchEvent(new Event("resize"));
    ',
    "card title"
  )
)
```
Again, I would be interested to know if there is a better way to do this, but posting this here in case anybody else reading this issue finds these workarounds useful.

**Comment by nstrayer** [comment]
I think the `tagAppendAttributes` solution posted above is the best solution to getting a card collapsed by default. 

It's worth noting that, as of #19 this will need to be run on `grid_card_old()` due to moving away from having our own cards in `gridlayout` and using `bslib`s `card()` component instead.  

If collapsibility is something you find particularly valuable and you need more advanced cards than what `grid_card_old()` provides, post an issue in the `bslib` repo. Feedback that that type of feature is desired (if it is) would be great for helping guide the API forward.
